# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_changementviewer.ui'
#
# Created: Thu Jan 19 12:28:54 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ChangementViewer(object):
    def setupUi(self, ChangementViewer):
        ChangementViewer.setObjectName(_fromUtf8("ChangementViewer"))
        ChangementViewer.setEnabled(True)
        ChangementViewer.resize(960, 100)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChangementViewer.sizePolicy().hasHeightForWidth())
        ChangementViewer.setSizePolicy(sizePolicy)
        ChangementViewer.setMinimumSize(QtCore.QSize(960, 100))
        ChangementViewer.setFloating(False)
        ChangementViewer.setWindowTitle(QtGui.QApplication.translate("ChangementViewer", "Changement viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.layoutWidget = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 951, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonPlay = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonPlay.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlay.sizePolicy().hasHeightForWidth())
        self.pushButtonPlay.setSizePolicy(sizePolicy)
        self.pushButtonPlay.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonPlay.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPlay.setIcon(icon)
        self.pushButtonPlay.setCheckable(True)
        self.pushButtonPlay.setChecked(False)
        self.pushButtonPlay.setFlat(True)
        self.pushButtonPlay.setObjectName(_fromUtf8("pushButtonPlay"))
        self.horizontalLayout.addWidget(self.pushButtonPlay)
        self.pushButtonBack = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon1)
        self.pushButtonBack.setIconSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.horizontalLayout.addWidget(self.pushButtonBack)
        self.timeSlide = QtGui.QSlider(self.layoutWidget)
        self.timeSlide.setMinimumSize(QtCore.QSize(0, 12))
        self.timeSlide.setMaximumSize(QtCore.QSize(16777215, 20))
        self.timeSlide.setAcceptDrops(False)
        self.timeSlide.setAutoFillBackground(False)
        self.timeSlide.setInputMethodHints(QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhPreferUppercase)
        self.timeSlide.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlide.setInvertedAppearance(False)
        self.timeSlide.setInvertedControls(False)
        self.timeSlide.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.timeSlide.setObjectName(_fromUtf8("timeSlide"))
        self.horizontalLayout.addWidget(self.timeSlide)
        self.pushButtonForward = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonForward.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonForward.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForward.setIcon(icon2)
        self.pushButtonForward.setFlat(True)
        self.pushButtonForward.setObjectName(_fromUtf8("pushButtonForward"))
        self.horizontalLayout.addWidget(self.pushButtonForward)
        self.layoutWidget1 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 951, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonToggleTime = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonToggleTime.sizePolicy().hasHeightForWidth())
        self.pushButtonToggleTime.setSizePolicy(sizePolicy)
        self.pushButtonToggleTime.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonToggleTime.setMaximumSize(QtCore.QSize(23, 23))
        self.pushButtonToggleTime.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/power_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/power_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonToggleTime.setIcon(icon3)
        self.pushButtonToggleTime.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonToggleTime.setCheckable(True)
        self.pushButtonToggleTime.setChecked(True)
        self.pushButtonToggleTime.setFlat(True)
        self.pushButtonToggleTime.setObjectName(_fromUtf8("pushButtonToggleTime"))
        self.horizontalLayout_2.addWidget(self.pushButtonToggleTime)
        self.btnSettings = QtGui.QPushButton(self.layoutWidget1)
        self.btnSettings.setText(QtGui.QApplication.translate("ChangementViewer", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSettings.setAutoDefault(True)
        self.btnSettings.setDefault(False)
        self.btnSettings.setObjectName(_fromUtf8("btnSettings"))
        self.horizontalLayout_2.addWidget(self.btnSettings)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setText(QtGui.QApplication.translate("ChangementViewer", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.labelDate = QtGui.QLabel(self.layoutWidget1)
        self.labelDate.setText(_fromUtf8(""))
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.horizontalLayout_2.addWidget(self.labelDate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonExportVideo = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonExportVideo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExportVideo.sizePolicy().hasHeightForWidth())
        self.pushButtonExportVideo.setSizePolicy(sizePolicy)
        self.pushButtonExportVideo.setText(QtGui.QApplication.translate("ChangementViewer", "Export Video", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonExportVideo.setObjectName(_fromUtf8("pushButtonExportVideo"))
        self.horizontalLayout_2.addWidget(self.pushButtonExportVideo)
        #ChangementViewer.setWidget(self.dockWidgetContents)

        self.retranslateUi(ChangementViewer)
        QtCore.QMetaObject.connectSlotsByName(ChangementViewer)

    def retranslateUi(self, ChangementViewer):
        pass

import resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ChangementViewer = QtGui.QDockWidget()
    ui = Ui_ChangementViewer()
    ui.setupUi(ChangementViewer)
    ChangementViewer.show()
    sys.exit(app.exec_())

